# Generated by Django 4.2.7 on 2023-11-08 18:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('house_number', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('model_product', models.CharField(max_length=250)),
                ('launch_date', models.DateField(default=datetime.date(2023, 11, 8))),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('debt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('type', models.CharField(choices=[('factory', 'factory'), ('distributor', 'distributor'), ('dealership', 'dealership'), ('retail_chain', 'retail_chain'), ('individual_entrepreneur', 'individual_entrepreneur')], default='factory', max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chainModel.address')),
                ('employee', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chainModel.supplier')),
                ('product', models.ManyToManyField(blank=True, to='chainModel.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
